CREATE DATABASE IF NOT EXISTS gki_menteng
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE gki_menteng;

DROP TABLE IF EXISTS dashboard_events;

CREATE TABLE IF NOT EXISTS news (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  date DATE NOT NULL,
  image VARCHAR(500) DEFAULT NULL,
  category VARCHAR(100) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS daily_reflections (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  reflection_date DATE NOT NULL UNIQUE,
  verse VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  author VARCHAR(255) NOT NULL,
  theme VARCHAR(255) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS site_stats (
  id TINYINT UNSIGNED PRIMARY KEY DEFAULT 1,
  members INT UNSIGNED NOT NULL DEFAULT 0,
  ministries INT UNSIGNED NOT NULL DEFAULT 0,
  volunteers INT UNSIGNED NOT NULL DEFAULT 0,
  events INT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS calendar_events (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  event_date DATE NOT NULL,
  time VARCHAR(20) NOT NULL,
  end_time VARCHAR(20) NOT NULL,
  location VARCHAR(255) NOT NULL,
  description TEXT,
  category VARCHAR(100) NOT NULL,
  color VARCHAR(20) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ministries (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  volunteer_count INT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS volunteers (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL,
  ministry VARCHAR(255) NOT NULL,
  schedule VARCHAR(255) NOT NULL,
  status ENUM('Scheduled', 'Available') NOT NULL DEFAULT 'Available',
  phone VARCHAR(50) DEFAULT NULL,
  email VARCHAR(255) DEFAULT NULL,
  experience VARCHAR(50) DEFAULT NULL,
  image VARCHAR(500) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sunday_schedules (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  schedule_date DATE NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sunday_services (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  schedule_id INT UNSIGNED NOT NULL,
  time_slot VARCHAR(50) NOT NULL,
  preacher VARCHAR(255) NOT NULL,
  worship_leader VARCHAR(255) NOT NULL,
  musicians JSON NOT NULL,
  hospitality JSON NOT NULL,
  multimedia VARCHAR(100) NOT NULL,
  sunday_school JSON NOT NULL,
  CONSTRAINT fk_sunday_services_schedule
    FOREIGN KEY (schedule_id) REFERENCES sunday_schedules(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS church_profile (
  id TINYINT UNSIGNED PRIMARY KEY DEFAULT 1,
  name VARCHAR(255) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  established VARCHAR(20) NOT NULL,
  address TEXT NOT NULL,
  phone VARCHAR(50) NOT NULL,
  email VARCHAR(255) NOT NULL,
  website VARCHAR(255) NOT NULL,
  denomination VARCHAR(255) NOT NULL,
  vision TEXT NOT NULL,
  mission JSON NOT NULL,
  history TEXT NOT NULL,
  description TEXT NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS pastoral_team (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  position VARCHAR(255) NOT NULL,
  education VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  image VARCHAR(500) DEFAULT NULL,
  sort_order INT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS church_activities (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  time VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  sort_order INT UNSIGNED NOT NULL DEFAULT 0
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('member', 'admin') NOT NULL DEFAULT 'member',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS auth_refresh_tokens (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  token_hash CHAR(64) NOT NULL,
  expires_at DATETIME NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  revoked_at DATETIME DEFAULT NULL,
  CONSTRAINT fk_refresh_tokens_user
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_refresh_token_hash (token_hash),
  INDEX idx_refresh_user (user_id)
) ENGINE=InnoDB;
